### ISSUE TITLE
[Typo] Duplicated `kind: Role` in `nginx-ingress/nginx-ingress-deployment-eni.yaml` start from line 199

### ISSUE THREAD

**Issue by jiahsingtan** [TencentCloudContainerTeam/manifest#1]
Duplicated `kind: Role` in `nginx-ingress/nginx-ingress-deployment-eni.yaml` start from line 199

https://github.com/TencentCloudContainerTeam/manifest/blob/master/nginx-ingress/nginx-ingress-deployment-eni.yaml#L199

**Comment by imroc** [comment]
Thanks, now it was been fixed.
